[package]
name = "trc"
version = "0.8.5"
edition = "2021"
resolver = "2"

[dependencies]
base64 = "0.22.1"
serde_json = "1.0.120"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls-webpki-roots", "http2"]}
bincode = "1.3.3"

[features]
test_mode = []

[dev-dependencies]
