[package]
name = "trc"
version = "0.8.5"
edition = "2021"
resolver = "2"

[dependencies]
mail-auth = { version = "0.4" }
base64 = "0.22.1"
serde_json = "1.0.120"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls-webpki-roots", "http2"]}
bincode = "1.3.3"
rtrb = "0.3.1"
parking_lot = "0.12.3"
tokio = { version = "1.23", features = ["net", "macros"] }
ahash = "0.8.11"
arc-swap = "1.7.1"

[features]
test_mode = []

[dev-dependencies]
